name: Semantic Release

on:
  push:
    branches:
      - master

jobs:
  semantic_release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            husky
            @semantic-release/npm
            @semantic-release/git
            conventional-changelog-conventionalcommits
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  deploy:
    name: Deploy
    needs: [semantic_release]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to production
        uses: fastndead/render-deploy-action@0.0.8-pre
        with:
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
          wait-for-success: true
